services:
  # バックエンドサービスの設定
  - name: my-recipes-backend
    type: web
    runtime: docker
    repo: https://github.com/tako-chan0511/my-recipes
    branch: hara_20250807_CICD
    plan: free
    healthCheckPath: /docs
    envVars:
      - fromGroup: my-recipes-secrets
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile

  # フロントエンドサービスの設定
  - name: my-recipes-frontend
    type: web
    runtime: docker
    repo: https://github.com/tako-chan0511/my-recipes
    branch: hara_20250807_CICD
    plan: free
    envVars:
      - key: PROXY_PASS
        value: http://my-recipes-backend:8686
      - key: RENDER_DNS_RESOLVER_IP
        fromService:
          type: pserv
          name: my-recipes-backend
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    dependsOn:
      - service: my-recipes-backend