# .github/workflows/ci.yml

name: CI/CD for my-recipes

on:
  push:
    branches:
      - hara_20250808_CI
  pull_request:
    branches:
      - hara_20250808_CI

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        run: pip install -r backend/requirements.txt

      - name: Run FastAPI tests
        # ↓↓↓ このenvセクションで、テスト環境であることを伝える ↓↓↓
        env:
          PYTHONPATH: ./backend
          RAKUTEN_APP_ID: ${{ secrets.RAKUTEN_APP_ID }}
        #   ENV: test # テスト実行中であることを示す環境変数を設定
        run: pytest backend/tests

  deploy-to-render:
    needs: test-and-build
    if: github.ref == 'refs/heads/hara_20250808_CI' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
